/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CurrentBalance: typeof import('./src/components/kpiCards/CurrentBalance.vue')['default']
    ExpensesCategoriesPieChart: typeof import('./src/components/ExpensesCategoriesPieChart.vue')['default']
    ExpensesList: typeof import('./src/components/ExpensesList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NewTransactionForm: typeof import('./src/components/NewTransactionForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TotalExpense: typeof import('./src/components/kpiCards/TotalExpense.vue')['default']
    TotalIncome: typeof import('./src/components/kpiCards/TotalIncome.vue')['default']
    TransactionsBarChart: typeof import('./src/components/TransactionsBarChart.vue')['default']
    TransactionsList: typeof import('./src/components/TransactionsList.vue')['default']
  }
}
